from django.contrib import admin
from .models import User, Inscription, Bibliography, InscriptionBibliography, EpigraphicReference, InscriptionReference, Category, Image, Abbreviation, AgeAtDeath, DivineSacredBeing, EmperorImperialFamily, Erasure, Findspot, Fragment, Organization, Person, PersonalName, PlaceName, Symbol, Word

# Register your models here.
admin.site.register(User)
admin.site.register(Inscription)
admin.site.register(Bibliography)
admin.site.register(InscriptionBibliography)
admin.site.register(EpigraphicReference)
admin.site.register(InscriptionReference)
admin.site.register(Category)
admin.site.register(Image)
admin.site.register(Abbreviation)
admin.site.register(AgeAtDeath)
admin.site.register(DivineSacredBeing)
admin.site.register(EmperorImperialFamily)
admin.site.register(Erasure)
admin.site.register(Findspot)
admin.site.register(Fragment)
admin.site.register(Organization)
admin.site.register(Person)
admin.site.register(PersonalName)
admin.site.register(PlaceName)
admin.site.register(Symbol)
admin.site.register(Word)