# Generated by Django 4.2.5 on 2023-11-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lepcismagna', '0002_inscription_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ageatdeath',
            options={'verbose_name_plural': 'ages at death'},
        ),
        migrations.AlterModelOptions(
            name='bibliography',
            options={'verbose_name_plural': 'bibliographies'},
        ),
        migrations.AlterModelOptions(
            name='emperorimperialfamily',
            options={'verbose_name_plural': 'emperors and imperial families'},
        ),
        migrations.AlterModelOptions(
            name='inscriptionbibliography',
            options={'verbose_name_plural': 'inscription bibliographies'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
    ]
