# Generated by Django 4.2.5 on 2023-11-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lepcismagna', '0003_alter_ageatdeath_options_alter_bibliography_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divinesacredbeing',
            options={'verbose_name_plural': 'divine and sacred beings'},
        ),
    ]
