# Generated by Django 4.2.5 on 2023-11-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepcismagna', '0004_alter_divinesacredbeing_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='abbreviation',
            name='inscriptions',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
        migrations.AddField(
            model_name='ageatdeath',
            name='inscriptions',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='inscriptions',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
        migrations.AddField(
            model_name='divinesacredbeing',
            name='inscriptions',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
        migrations.AddField(
            model_name='emperorimperialfamily',
            name='inscriptions',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
        migrations.AddField(
            model_name='erasure',
            name='inscriptions',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
        migrations.AddField(
            model_name='findspot',
            name='inscriptions',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
        migrations.AddField(
            model_name='fragment',
            name='inscriptions',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
        migrations.AddField(
            model_name='organization',
            name='inscriptions',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
        migrations.AddField(
            model_name='person',
            name='inscriptions',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
        migrations.AddField(
            model_name='personalname',
            name='inscriptions',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
        migrations.AddField(
            model_name='placename',
            name='inscriptions',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='inscriptions',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
        migrations.AddField(
            model_name='word',
            name='inscriptions',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
    ]
