# Generated by Django 4.2.5 on 2023-11-08 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lepcismagna', '0006_remove_abbreviation_inscriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='entry_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='lepcismagna.user'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='images',
            field=models.ManyToManyField(blank=True, to='lepcismagna.image'),
        ),
    ]
