# Generated by Django 4.2.5 on 2023-11-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepcismagna', '0007_inscription_entry_creator_inscription_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='associated_inscr',
            field=models.ManyToManyField(blank=True, to='lepcismagna.inscription'),
        ),
    ]
