# Generated by Django 4.2.5 on 2023-11-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lepcismagna', '0008_alter_inscription_associated_inscr'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
