# Generated by Django 4.2.5 on 2023-11-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lepcismagna', '0011_remove_inscription_entry_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='inscription_id',
        ),
        migrations.AddField(
            model_name='image',
            name='reference_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lepcismagna.inscription'),
        ),
    ]
